version: '3.7'
services:
    mysql:
        image: mysql:5.7
        container_name: mysql
        env_file:
            - ./mysql.env
        volumes:
            - ./storage/mysql:/var/lib/mysql
    app:
        build: ./src
        container_name: app
        ports:
            - 8000:80
        volumes:
            - ./src:/var/www
            - ./storage/app:/var/www/storage/app
            - ./storage/logs:/var/www/storage/logs