version: '3.7'
services:
    mysql:
        container_name: mysql
        image: mysql:5.7
        env_file:
            - ./config/mysql.env
        volumes:
            - ./storage/mysql:/var/lib/mysql
    app:
        container_name: app
        image: creativitykills/nginx-php-server:latest
        ports:
            - 8000:80
        volumes:
            - ./src:/var/www
            - ./storage/app:/var/www/storage/app
            - ./storage/logs:/var/www/storage/logs